"""
API Generator Module

Two modes:
  1. Single-route generation (LLM-based) — given a validated SQL query,
     produce one FastAPI route.  Used by the main query pipeline.

  2. Full CRUD generation (deterministic) — given a table name and live
     schema, produce a complete GET/GET-by-id/POST/PUT/DELETE file and
     save it to generated/apis/<table>.py.
"""
import os
import re
import textwrap
from pathlib import Path

from llm_client import chat

# Directory where per-table CRUD files are written
GENERATED_APIS_DIR = Path(__file__).parent / "generated" / "apis"

# ── mode 1: single route from SQL (LLM) ──────────────────────────────────────

API_SYSTEM_PROMPT = """You are an expert FastAPI developer.
You will be given a validated MySQL query and a description of what it does.
Your job is to generate a complete, working FastAPI route for this operation.

Rules:
- Output ONLY valid Python code — no explanation, no markdown fences.
- Use mysql-connector-python for DB access (not SQLAlchemy).
- NEVER use async def — use plain def (all DB calls are synchronous).
- Only include a Pydantic model if it is actually used in the route (POST/PUT body).
- ALWAYS use cursor = conn.cursor(dictionary=True) so results are dicts, not tuples.
- ALWAYS handle empty results: if not result: raise HTTPException(status_code=404, ...).
- Use parameterized queries with %s placeholders — never string formatting.
- Use snake_case for function names and route paths.
- The route must be a complete @router.get/post/put/delete decorated function.
- Import only from fastapi, pydantic, and mysql.connector.
- Assume a `get_connection()` function is available from `database` module.
- Always close cursor and connection in a finally block.

Template to follow:
from fastapi import APIRouter, HTTPException
from mysql.connector import Error
from database import get_connection

router = APIRouter()

@router.get("/example")
def example_route(param: int):
    conn = None
    try:
        conn = get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT ... WHERE id = %s", (param,))
        result = cursor.fetchall()
        if not result:
            raise HTTPException(status_code=404, detail="No records found")
        return {"data": result}
    except HTTPException:
        raise
    except Error as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if conn and conn.is_connected():
            cursor.close()
            conn.close()
"""


def generate_api_route(user_request: str, sql: str) -> str:
    """
    LLM-generated FastAPI route for a validated SQL query.
    Used by the main pipeline when generate_api=True.
    """
    user_message = f"""User request:
{user_request}

Working MySQL query:
{sql}

Generate a FastAPI route for this operation:"""

    raw = chat(API_SYSTEM_PROMPT, user_message, temperature=0.2)
    raw = re.sub(r"```(?:python)?", "", raw, flags=re.IGNORECASE)
    raw = raw.replace("```", "").strip()
    return raw


def generate_full_api_file(routes: list[dict]) -> str:
    """
    Combine multiple generated routes into a single downloadable FastAPI file.
    """
    header = textwrap.dedent('''\
        """
        Auto-generated FastAPI CRUD API
        Generated by the Self-Correcting LLM Framework
        """
        from fastapi import FastAPI, HTTPException, APIRouter
        from pydantic import BaseModel
        from typing import Optional, List
        import mysql.connector
        from database import get_connection

        app = FastAPI(title="Auto-Generated API", version="1.0.0")
        router = APIRouter()


        @app.get("/health")
        def health_check():
            return {"status": "ok", "service": "generated-api"}

        ''')
    footer = textwrap.dedent('''\


        app.include_router(router)

        if __name__ == "__main__":
            import uvicorn
            uvicorn.run(app, host="0.0.0.0", port=8000)
        ''')

    route_blocks = []
    for i, r in enumerate(routes):
        route_blocks.append(f"# Route {i + 1}: {r['request']}")
        route_blocks.append(r["route_code"])
        route_blocks.append("")

    return header + "\n".join(route_blocks) + footer


# ── mode 2: full CRUD from schema (deterministic) ────────────────────────────

def detect_crud_table(user_request: str, schema: dict) -> str | None:
    """
    Return the table name if the user is asking for CRUD API generation,
    otherwise return None.

    Recognised patterns (case-insensitive):
      "create crud apis for <table>"
      "generate crud for <table>"
      "build api for <table>"
      "create api for <table>"
      "generate api for <table>"
      "create rest api for <table>"
      "make crud for <table>"
    """
    request = user_request.strip().lower()
    pattern = re.compile(
        r"(?:create|generate|build|make)\s+"
        r"(?:crud\s+)?(?:rest\s+)?(?:api|apis|endpoints?)\s+"
        r"(?:for|on|of)\s+([a-z_][\w\s]*)",
        re.IGNORECASE,
    )
    match = pattern.search(request)
    if not match:
        return None

    raw_entity = match.group(1).strip().split()[0]  # first word only
    return _resolve_table(raw_entity, schema)


def generate_crud_api(table_name: str, schema: dict) -> tuple[str, str]:
    """
    Deterministically generate a complete CRUD FastAPI router for a table.

    Args:
        table_name: Exact table name as it appears in the schema.
        schema:     Full schema dict from schema_retriever.get_schema().

    Returns:
        (code: str, filepath: str)  — the generated Python source and the
        path where it was written.
    """
    table_info = schema.get(table_name, {})
    columns = table_info.get("columns", [])
    if not columns:
        raise ValueError(f"Table '{table_name}' not found in schema or has no columns.")

    pk_col = _pick_pk(columns)
    pk_type = _mysql_to_python(pk_col["type"]) if pk_col else "int"
    pk_name = pk_col["name"] if pk_col else "id"

    # writable columns = all non-PK columns (PK is auto-set on insert)
    writable = [c for c in columns if c["name"] != pk_name]

    model_class   = _pascal(table_name)
    create_model  = f"{model_class}Create"
    update_model  = f"{model_class}Update"
    route_prefix  = f"/{table_name}"
    tag           = table_name

    code = _render_file(
        table_name=table_name,
        pk_name=pk_name,
        pk_type=pk_type,
        columns=columns,
        writable=writable,
        model_class=model_class,
        create_model=create_model,
        update_model=update_model,
        route_prefix=route_prefix,
        tag=tag,
    )

    GENERATED_APIS_DIR.mkdir(parents=True, exist_ok=True)
    filepath = GENERATED_APIS_DIR / f"{table_name}.py"
    filepath.write_text(code, encoding="utf-8")
    return code, str(filepath)


def list_generated_apis() -> list[str]:
    """Return the table names for which a CRUD file has been generated."""
    if not GENERATED_APIS_DIR.exists():
        return []
    return [
        p.stem
        for p in sorted(GENERATED_APIS_DIR.glob("*.py"))
        if p.stem != "__init__"
    ]


# ── rendering helpers ─────────────────────────────────────────────────────────

def _render_file(
    table_name, pk_name, pk_type, columns, writable,
    model_class, create_model, update_model, route_prefix, tag,
) -> str:
    """
    Build the CRUD file line-by-line to avoid f-string multi-line
    substitution indentation issues that arise with textwrap.dedent.
    """
    insert_cols = ", ".join(c["name"] for c in writable)
    insert_phs  = ", ".join("%s" for _ in writable)
    insert_vals = ", ".join(f"payload.{c['name']}" for c in writable)
    fn = table_name.lower()

    L = []  # lines

    # header
    L += [
        '"""',
        f"CRUD API for table: {table_name}",
        "Auto-generated by the Self-Correcting LLM SQL Agent Framework",
        f'Do not edit manually -- regenerate via: "create CRUD APIs for {table_name}"',
        '"""',
        "from fastapi import APIRouter, HTTPException",
        "from pydantic import BaseModel",
        "from typing import Optional",
        "from database import get_connection",
        "",
        f'router = APIRouter(prefix="{route_prefix}", tags=["{tag}"])',
        "",
        "",
        "# -- Pydantic models --------------------------------------------------",
        "",
    ]

    # Create model
    L.append(f"class {create_model}(BaseModel):")
    if writable:
        for col in writable:
            py_type = _mysql_to_python(col["type"])
            if col.get("nullable", True):
                L.append(f"    {col['name']}: Optional[{py_type}] = None")
            else:
                L.append(f"    {col['name']}: {py_type}")
    else:
        L.append("    pass")
    L.append("")

    # Update model (all Optional for partial updates)
    L.append(f"class {update_model}(BaseModel):")
    if writable:
        for col in writable:
            py_type = _mysql_to_python(col["type"])
            L.append(f"    {col['name']}: Optional[{py_type}] = None")
    else:
        L.append("    pass")
    L += ["", ""]

    # GET / — list all
    L += [
        "# -- GET / — list all rows -------------------------------------------",
        "",
        f'@router.get("/", summary="List all {table_name} records")',
        f"def list_{fn}(limit: int = 50, offset: int = 0):",
        "    conn = None",
        "    try:",
        "        conn = get_connection()",
        "        cursor = conn.cursor(dictionary=True)",
        f'        cursor.execute("SELECT * FROM {table_name} LIMIT %s OFFSET %s", (limit, offset))',
        "        rows = cursor.fetchall()",
        "        if not rows:",
        f'            raise HTTPException(status_code=404, detail="No {table_name} records found")',
        f'        return {{"{table_name}": rows}}',
        "    except HTTPException:",
        "        raise",
        "    except Exception as exc:",
        "        raise HTTPException(status_code=500, detail=str(exc))",
        "    finally:",
        "        if conn and conn.is_connected():",
        "            cursor.close()",
        "            conn.close()",
        "",
        "",
    ]

    # GET /{id} — fetch one
    L += [
        f"# -- GET /{{{pk_name}}} — fetch one row --------------------------------",
        "",
        f'@router.get("/{{{pk_name}}}", summary="Get a {table_name} record by {pk_name}")',
        f"def get_{fn}({pk_name}: {pk_type}):",
        "    conn = None",
        "    try:",
        "        conn = get_connection()",
        "        cursor = conn.cursor(dictionary=True)",
        f'        cursor.execute("SELECT * FROM {table_name} WHERE {pk_name} = %s", ({pk_name},))',
        "        row = cursor.fetchone()",
        "        if not row:",
        f'            raise HTTPException(status_code=404, detail="{table_name} record not found")',
        "        return row",
        "    except HTTPException:",
        "        raise",
        "    except Exception as exc:",
        "        raise HTTPException(status_code=500, detail=str(exc))",
        "    finally:",
        "        if conn and conn.is_connected():",
        "            cursor.close()",
        "            conn.close()",
        "",
        "",
    ]

    # POST / — create
    L += [
        "# -- POST / — create a new row ----------------------------------------",
        "",
        f'@router.post("/", status_code=201, summary="Create a new {table_name} record")',
        f"def create_{fn}(payload: {create_model}):",
        "    conn = None",
        "    try:",
        "        conn = get_connection()",
        "        cursor = conn.cursor()",
        f'        cursor.execute(',
        f'            "INSERT INTO {table_name} ({insert_cols}) VALUES ({insert_phs})",',
        f"            ({insert_vals},),",
        "        )",
        "        conn.commit()",
        '        return {"id": cursor.lastrowid, "message": "Created successfully"}',
        "    except Exception as exc:",
        "        if conn and conn.is_connected():",
        "            conn.rollback()",
        "        raise HTTPException(status_code=400, detail=str(exc))",
        "    finally:",
        "        if conn and conn.is_connected():",
        "            cursor.close()",
        "            conn.close()",
        "",
        "",
    ]

    # PUT /{id} — update
    allowed_cols = repr([c["name"] for c in writable])
    L += [
        f"# -- PUT /{{{pk_name}}} — update a row ----------------------------------",
        "",
        f'@router.put("/{{{pk_name}}}", summary="Update a {table_name} record")',
        f"def update_{fn}({pk_name}: {pk_type}, payload: {update_model}):",
        f"    _ALLOWED_COLS = {allowed_cols}",
        "    updates = {k: v for k, v in payload.dict().items() if v is not None and k in _ALLOWED_COLS}",
        "    if not updates:",
        '        raise HTTPException(status_code=400, detail="No fields provided to update")',
        '    set_clause = ", ".join(f"`{col}` = %s" for col in updates)',
        "    conn = None",
        "    try:",
        "        conn = get_connection()",
        "        cursor = conn.cursor()",
        "        cursor.execute(",
        f'            f"UPDATE `{table_name}` SET {{set_clause}} WHERE `{pk_name}` = %s",',
        f"            (*updates.values(), {pk_name}),",
        "        )",
        "        conn.commit()",
        "        if cursor.rowcount == 0:",
        f'            raise HTTPException(status_code=404, detail="{table_name} record not found")',
        '        return {"updated": cursor.rowcount, "message": "Updated successfully"}',
        "    except HTTPException:",
        "        raise",
        "    except Exception as exc:",
        "        if conn and conn.is_connected():",
        "            conn.rollback()",
        "        raise HTTPException(status_code=400, detail=str(exc))",
        "    finally:",
        "        if conn and conn.is_connected():",
        "            cursor.close()",
        "            conn.close()",
        "",
        "",
    ]

    # DELETE /{id} — delete
    L += [
        f"# -- DELETE /{{{pk_name}}} — remove a row -------------------------------",
        "",
        f'@router.delete("/{{{pk_name}}}", summary="Delete a {table_name} record")',
        f"def delete_{fn}({pk_name}: {pk_type}):",
        "    conn = None",
        "    try:",
        "        conn = get_connection()",
        "        cursor = conn.cursor()",
        f'        cursor.execute("DELETE FROM {table_name} WHERE {pk_name} = %s", ({pk_name},))',
        "        conn.commit()",
        "        if cursor.rowcount == 0:",
        f'            raise HTTPException(status_code=404, detail="{table_name} record not found")',
        '        return {"deleted": cursor.rowcount, "message": "Deleted successfully"}',
        "    except HTTPException:",
        "        raise",
        "    except Exception as exc:",
        "        if conn and conn.is_connected():",
        "            conn.rollback()",
        "        raise HTTPException(status_code=400, detail=str(exc))",
        "    finally:",
        "        if conn and conn.is_connected():",
        "            cursor.close()",
        "            conn.close()",
        "",
    ]

    return "\n".join(L)


def _mysql_to_python(mysql_type: str) -> str:
    t = (mysql_type or "").lower().split("(")[0].strip()
    int_types  = {"int", "tinyint", "smallint", "mediumint", "bigint", "integer"}
    float_types = {"float", "double", "decimal", "numeric", "real"}
    bool_types  = {"bool", "boolean", "bit"}
    if t in int_types:
        return "int"
    if t in float_types:
        return "float"
    if t in bool_types:
        return "bool"
    return "str"


def _pick_pk(columns: list[dict]) -> dict | None:
    for col in columns:
        if col.get("key") == "PRI":
            return col
    return columns[0] if columns else None


def _pascal(name: str) -> str:
    return "".join(word.capitalize() for word in name.split("_"))


def _resolve_table(entity: str, schema: dict) -> str | None:
    lookup = {k.lower(): k for k in schema}
    cleaned = entity.lower().replace(" ", "_")
    candidates = [
        cleaned,
        cleaned.rstrip("s"),
        cleaned + "s",
        cleaned[:-1] + "ies" if cleaned.endswith("y") else cleaned,
        cleaned[:-3] + "y" if cleaned.endswith("ies") else cleaned,
    ]
    for c in candidates:
        if c in lookup:
            return lookup[c]
    return None
